#+TITLE:  SuperNEMO \alpha delayed tracks studies
#+AUTHOR: Xavier Garrido
#+DATE:   2015-05-29
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration to study \alpha delayed tracks such
as comparison between the reconstructed track length and the simulated particle
path.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_alpha_delayed_studies]]
under =git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_alpha_delayed_studies_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* Module declaration

The next item holds the configuration of the module. The second item is related
to histogram declarations.

** Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_alpha_delayed_studies_module.conf
:END:

The module name to be used when processing a file is
=alpha_delayed_studies_module=.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Declaration & description
#+BEGIN_SRC sh
  [name="alpha_delayed_studies_module" type="snemo::analysis::snemo_alpha_delayed_studies_module"]

  #@description A SuperNEMO module to evaluate alpha delayed reconstruction efficiency
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "debug"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram declarations][here]]
#+BEGIN_SRC shell
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC

*** Histogram storage
All histograms generated by =snemo_alpha_delayed_studies= module can be stored
inside ROOT files or XML archives.
#+BEGIN_SRC shell
  #@description The ouput file where to store the histograms
  Histo.output_files : string[2] as path =                  \
      "/tmp/${USER}/snemo.d/snemo_alpha_delayed_studies_histos.root" \
      "/tmp/${USER}/snemo.d/snemo_alpha_delayed_studies_histos.xml"
#+END_SRC
*** Histogram templates
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram.
#+BEGIN_SRC shell
  #@description The ouput file where to store the histograms
  Histo.template_files : string[1] as path = \
      "@SNEMO_ANALYSIS_MODULES_DIR@/snemo_alpha_delayed_studies_histogram_templates.conf"
#+END_SRC
** Histogram declarations
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_alpha_delayed_studies_histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section.

*** Mandatory preamble
#+BEGIN_SRC shell
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** \alpha delayed track length distribution
#+BEGIN_SRC shell
  [name="1e1a::delta_track_length" type="mygsl::histogram_1d"]
  #@config The histogram of the relative difference between rec./sim. alpha track length

  #@description The group of the histogram (optional)
  group : string = "1e1a::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 50

  #@description The lower bound of the histogram
  min : real = -1.0

  #@description The upper bound of the histogram
  max : real = +1.0

  #@description The X axis label
  display.xaxis.label : string = "#ell"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC
