#+TITLE:  SuperNEMO - Bremsstrahlung studies
#+AUTHOR: Xavier Garrido
#+DATE:   2014-09-16
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration + source code to study the
bremsstrahlung produced within source foil. It especially produces plots of the
energy of the primary electron + gamma from bremsstrahlung or the angular
distribution.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_bremsstrahlung_studies]]
under =git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_bremsstrahlung_studies_module.*= source code as well as a
=CMakeLists.txt= file in order to compile, build and install the module
following =cmake= rules.

* Module configuration
:PROPERTIES:
:MKDIRP: yes
:END:

The next item holds the configuration for the module itself. The second item is
related to histogram declarations.

** Module declaration
:PROPERTIES:
:TANGLE: ../config/snemo_bremsstrahlung_studies_module.conf
:END:

The module name is =bremsstrahlung_studies_module= which is needed when using
=bxdpp_processing= as explained in the top [[../README.org][README]] file.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC sh
  [name="bremsstrahlung_studies_module" type="analysis::snemo_bremsstrahlung_module"]

  #@description A SuperNEMO module to study bremsstrahlung production within source foil
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "error"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram service][here]]
#+BEGIN_SRC sh
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC
*** Histogram storage
All histograms generated by this module can be stored inside ROOT files or XML
archives.
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_output_files : string[2] as path =                            \
      "/tmp/${USER}/snemo.d/snemo_bremsstrahlung_studies_histos.root" \
      "/tmp/${USER}/snemo.d/snemo_bremsstrahlung_studies_histos.xml"
#+END_SRC

*** Histogram template location
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram. For instance, plotting the vertex position distributions
only implies 3 histogram templates for each of the 3 cartesian coordinates
$x,y,z$ (see [[Histogram declarations][below]]).
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_template_files : string[1] as path = \
      "@SNEMO_SIMULATION_MODULES_DIR@/snemo_bremsstrahlung_studies_histogram_templates.conf"
#+END_SRC
** Histogram declarations
:PROPERTIES:
:TANGLE: ../config/snemo_bremsstrahlung_studies_histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section. There are mostly /template/ histogram in such way, their declarations
may be used as templates for several histograms.

*** Mandatory preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Energy distribution
**** Primary electron
#+BEGIN_SRC sh
  [name="electron_energy" type="mygsl::histogram_1d"]
  #@config The histogram of the energy of primary electrons

  #@description The group of the histogram (optional)
  group : string = "energy_distribution"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "Energy"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "dN/dE"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real as energy = 0.0 keV

  #@description The upper bound of the histogram
  max : real as energy = 3200.0 keV
#+END_SRC
**** \gamma bremsstrahlung
#+BEGIN_SRC sh
  [name="gamma_energy" type="mygsl::histogram_1d"]
  #@config The histogram of the energy of gammas

  #@description The group of the histogram (optional)
  group : string = "energy_distribution"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "Energy"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "dN/dE"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real as energy = 0.0 keV

  #@description The upper bound of the histogram
  max : real as energy = 3200.0 keV
#+END_SRC
