#+TITLE:  SuperNEMO - Foil vertex distribution
#+AUTHOR: Xavier Garrido
#+DATE:   2014-06-16
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration + source code to show the vertex
distribution on the source foil. It builds a 2D visualization histogram by
looking into simulated data /i.e./ within true vertex position or reconstructed
data. Thus, it can be used to compare the two distributions, simulated vs. real
to exhibit detector reconstruction efficiency. An example of
the use of this module is provided in this [[http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=2732][presentation]].

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_foil_vertex_distribution]] under
=git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_foil_vertex_distribution_module.*= source code as well as a
=CMakeLists.txt= file in order to compile, build and install the module
following =cmake= rules.

* Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_foil_vertex_distribution_module.conf
:END:

The next item holds the configuration for this module. The module name is
=foil_vertex_distribution_module= which is needed when using =bxdpp_processing=
as explained in the top [[file:../README.org::*Use and execute a module][README]] file.

** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
  #+END_SRC
** Declaration & description
#+BEGIN_SRC sh
  [name="foil_vertex_distribution_module" type="analysis::snemo_foil_vertex_distribution_module"]

  #@description A SuperNEMO module to plot the vertex distribution on the source foil
#+END_SRC

** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "trace"
#+END_SRC
** Bank label
The bank record label where to look in.
#+BEGIN_SRC sh
  #@description The data bank label
  bank_label : string = "SD"
#+END_SRC

** Histogram service label
Set the same histogram service label as defined [[file:../README.org::*Histogram service][here]]
#+BEGIN_SRC sh
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC
** Histogram storage
All histograms generated by =snemo_bb0nu_studies= module can be stored inside
ROOT files or XML archives.
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_output_files : string[2] as path =                              \
      "/tmp/${USER}/snemo.d/snemo_foil_vertex_distribution_histos.root" \
      "/tmp/${USER}/snemo.d/snemo_foil_vertex_distribution_histos.xml"
#+END_SRC

** Histogram template location
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram. For instance, plotting the energy distributions of several
channels may only need one general histogram definition which gives the x-axis
boundaries and x-binning (see [[Histogram declarations][below]]).
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_template_files : string[1] as path = \
      "@SNEMO_SIMULATION_MODULES_DIR@/snemo_foil_vertex_distribution_templates.conf"
#+END_SRC

* Histogram declaration
:PROPERTIES:
:TANGLE: ../config/snemo_foil_vertex_distribution_templates.conf
:END:

The histogram declaration /i.e./ name, boundaries, binning... are set in this
section. There are mostly /template/ histogram in such way, their declarations
may be used as templates for several histograms. For
=snemo_foil_vertex_distribution_module= only one 2D histogram needs to be
declared which boundaries represent foil design boundaries /i.e./ \pm 2500 mm \times
\pm1500 mm.

** Mandatory preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

** 2D vertex distribution template
#+BEGIN_SRC sh
  [name="foil_vertex_distribution_template" type="mygsl::histogram_2d"]
  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  x.linear : boolean = 1

  #@description The X bin unit
  x.unit : string = "mm"

  #@description The lower bound of the histogram
  x.min : real = -2500.0

  #@description The upper bound of the histogram
  x.max : real = +2500.0

  #@description The upper bound of the histogram
  x.number_of_bins : integer = 100

  #@description The linear mode (default)
  y.linear : boolean = 1

  #@description The X bin unit
  y.unit : string = "mm"

  #@description The lower bound of the histogram
  y.min : real = -1500.0

  #@description The upper bound of the histogram
  y.max : real = +1500.0

  #@description The upper bound of the histogram
  y.number_of_bins : integer = 100

  #@description The X axis label
  display.xaxis.label : string = "y"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "mm"

  #@description The Y axis label
  display.yaxis.label : string = "z"

  #@description The Y axis unit for display (a standard unit, typically SI or CLHEP)
  display.yaxis.unit : string = "mm"
#+END_SRC
