#+TITLE:  SuperNEMO - Vertex reconstruction
#+AUTHOR: Xavier Garrido
#+DATE:   2014-06-13
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration + source code to study the
vertex reconstruction of particle track in SuperNEMO. It especially produces
plots of vertex position resolution on the source foil as well as on calorimeter
wall surface.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_vertex_resolution]]
under =git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_vertex_resolution_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* Module configuration
:PROPERTIES:
:MKDIRP: yes
:END:

The next item holds the configuration for the module itself. The second item is
related to histogram declarations.

** Module declaration
:PROPERTIES:
:TANGLE: ../config/snemo_vertex_resolution_module.conf
:END:

The module name is =vertex_resolution_module= which is needed when using
=bxdpp_processing= as explained in the top [[../README.org][README]] file.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC sh
  [name="vertex_resolution_module" type="analysis::snemo_vertex_resolution_module"]

  #@description A SuperNEMO module to show the vertex position resolution
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "notice"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram service][here]]
#+BEGIN_SRC sh
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC
*** Histogram storage
All histograms generated by this module can be stored inside ROOT files or XML
archives.
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_output_files : string[2] as path =                       \
      "/tmp/${USER}/snemo.d/snemo_vertex_resolution_histos.root" \
      "/tmp/${USER}/snemo.d/snemo_vertex_resolution_histos.xml"
#+END_SRC

# Histograms done from a previous run of the module can be load at startup. This
# is useful when processing of a huge collection of files has been done and energy
# distribution as well as efficiency have been computed : then the output
# histograms can be set as new input for the =histogram_service= in such way, the
# processing does not to be redo for these peculiar files.
# #+BEGIN_SRC sh
#   # #@description The input file from where to load the histograms
#   # Histo_input_file : string as path = \
#   #     "/tmp/${USER}/snemo.d/snemo_bb0nu_halflife_limit_histos.saved.xml"
# #+END_SRC

*** COMMENT Histogram templates
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram. For instance, plotting the energy distributions of several
channels may only need one general histogram definition which gives the x-axis
boundaries and x-binning (see [[Histogram declarations][below]]).
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_template_files : string[1] as path = \
      "@SNEMO_SIMULATION_MODULES_DIR@/snemo_bb0nu_histogram_templates.conf"
#+END_SRC
** COMMENT Histogram declarations
:PROPERTIES:
:TANGLE: ../config/snemo_vertex_resolution_histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section. There are mostly /template/ histogram in such way, their declarations
may be used as templates for several histograms. For instance, the [[Energy
template]] defines an histogram that can be mimic by different analysis channels
/i.e./ 0\nu energy distribution to background energy distribution.

*** Mandatory preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Energy template
#+BEGIN_SRC sh
  [name="energy_template" type="mygsl::histogram_1d"]
  #@config The histogram template of the energy distribution

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}$E$_\text{calibrated}"

  #@description The Y axis label
  display.yaxis.label : string = "dN/dE [A.U.]"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real as energy = 2000.0 keV

  #@description The upper bound of the histogram
  max : real as energy = 3200.0 keV
#+END_SRC
*** Efficiency template
#+BEGIN_SRC sh
  [name="efficiency_template" type="mygsl::histogram_1d"]
  #@config The histogram template of the energy selection efficiency

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}\text{E}_\text{calibrated}\geq\text{E}_\text{cut}"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "efficiency"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The lower bound of the histogram
  min : real as energy = 2000.0 keV

  #@description The upper bound of the histogram
  max : real as energy = 3200.0 keV
#+END_SRC

*** Halflife limit template
#+BEGIN_SRC sh
  [name="halflife_template" type="mygsl::histogram_1d"]
  #@config The histogram template of the halflife limit values

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}\text{E}_\text{calibrated}\geq\text{E}_\text{cut}"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "halflife limit"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The lower bound of the histogram
  min : real as energy = 2000.0 keV

  #@description The upper bound of the histogram
  max : real as energy = 3200.0 keV
#+END_SRC
