#+TITLE:  SuperNEMO control plot module
#+AUTHOR: Xavier Garrido
#+DATE:   2014-05-23
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration to run SuperNEMO simulations and
to produce several "control" plots. It provides one SN@ilWare module which
automatically plot physical quantities from different data banks. For example,
it shows the distribution of the number of Geiger hits from the =simulated_data=
bank and from the =calibrated_data= bank. The purpose of this module is to have
some fundamental key plots to check differences between software releases, new
software implementations and so on.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_control_plot]] under
=git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_control_plot_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* Module declaration

The next item holds the configuration of the module. The second item is related
to histogram declarations.

** Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_control_plot_module.conf
:END:

The module name to be used when processing a file is =scp_module=.

*** File preamble
#+BEGIN_SRC shell
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC shell
  [name="snemo_control_plot" type="snemo::analysis::snemo_control_plot_module"]

  #@description A SuperNEMO module to plot key quantities from data banks
#+END_SRC

*** Logging priority
#+BEGIN_SRC shell
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram service][here]]
#+BEGIN_SRC shell
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC
*** Histogram storage
All histograms generated by =snemo_control_plot= module can be stored inside
ROOT files or XML archives.
#+BEGIN_SRC shell
  #@description The ouput file where to store the histograms
  Histo.output_files : string[2] as path =                  \
      "/tmp/${USER}/snemo.d/snemo_control_plot_histos.root" \
      "/tmp/${USER}/snemo.d/snemo_control_plot_histos.xml"
#+END_SRC
*** Histogram templates
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram. For instance, plotting the energy distributions of several
channels may only need one general histogram definition which gives the x-axis
boundaries and x-binning.
#+BEGIN_SRC shell
  #@description The ouput file where to store the histograms
  Histo.template_files : string[1] as path = \
      "@SNEMO_ANALYSIS_MODULES_DIR@/snemo_control_plot_histogram_templates.conf"
#+END_SRC

*** Plotter declarations
#+BEGIN_SRC shell
  plotters : string[4] = "SDP" "CDP" "TCDP" "TTDP"
#+END_SRC
**** Simulated data plotter
#+BEGIN_SRC shell
  #@description Logging flag
  SDP.logging.priority : string = "error"
#+END_SRC

**** Tracker trajectory data plotter
#+BEGIN_SRC shell
  #@description Logging flag
  TTDP.logging.priority : string = "error"
#+END_SRC

** Histogram declarations
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_control_plot_histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section which is organized by data bank related plots. There are two kinds of
histograms:
- /unique/ histogram, dedicated to one task and used only one time,
- /template/ histogram which may be used by several data bank.
For example, to plot the distribution of the number of Geiger hits which can be
done for =simulated_data= and =calibrated_data= banks, we use *one* histogram
template that define boundaries, binning, axis titles... The /template/
histograms all belong to the =__template= group.

*** Mandatory preamble
#+BEGIN_SRC shell
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Simulated data bank histograms
**** Number of Geiger hits
#+BEGIN_SRC shell
  [name="SD::ngghits" type="mygsl::histogram_1d"]
  #@config The histogram of the number of MC Geiger hits

  #@description The group of the histogram (optional)
  group : string = "SD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 50

  #@description The lower bound of the histogram
  min : real = -0.5

  #@description The upper bound of the histogram
  max : real = 99.5

  #@description The X axis label
  display.xaxis.label : string = "Ngg"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

**** Number of calorimeter hits
#+BEGIN_SRC shell
  [name="SD::ncalohits" type="mygsl::histogram_1d"]
  #@config The histogram of the number of MC calo hits

  #@description The group of the histogram (optional)
  group : string = "SD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 10

  #@description The lower bound of the histogram
  min : real = -0.5

  #@description The upper bound of the histogram
  max : real = 9.5

  #@description The X axis label
  display.xaxis.label : string = "Ncalo"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

*** Calibrated data bank histograms
**** Number of calibrated tracker hits
#+BEGIN_SRC shell
  [name="CD::ngghits" type="mygsl::histogram_1d"]
  #@config The histogram of the number of calibrated tracker hits

  #@description The title of the histogram (optional)
  title : string = "Number of calibrated tracker hits"

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The lower bound of the histogram
  min : real = -0.5

  #@description The upper bound of the histogram
  max : real = 99.5

  #@description The X axis label
  display.xaxis.label : string = "N_{calib.}(tracker)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

**** Number of calibrated calorimeter hits
#+BEGIN_SRC shell
  [name="CD::ncalohits" type="mygsl::histogram_1d"]
  #@config The histogram of the number of calibrated calorimeter hits

  #@description The title of the histogram (optional)
  title : string = "Number of calibrated calorimeter hits"

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 10

  #@description The lower bound of the histogram
  min : real = -0.5

  #@description The upper bound of the histogram
  max : real = 9.5

  #@description The X axis label
  display.xaxis.label : string = "N_{calib.}(calorimeter)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

**** Distribution of drift radius
#+BEGIN_SRC shell
  [name="CD::drift_radius" type="mygsl::histogram_1d"]
  #@config The histogram of the Geiger cell radius

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 100

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "mm"

  #@description The lower bound of the histogram
  min : real as length = 0 mm

  #@description The upper bound of the histogram
  max : real as length = 25 mm

  #@description The X axis label
  display.xaxis.label : string = "r_{calib.}(tracker)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC
**** Distribution of drift radius error
#+BEGIN_SRC shell
  [name="CD::drift_radius_error" type="mygsl::histogram_1d"]
  #@config The histogram of the Geiger cell radius error

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 100

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "mm"

  #@description The lower bound of the histogram
  min : real as length = 0 mm

  #@description The upper bound of the histogram
  max : real as length = 1 mm

  #@description The X axis label
  display.xaxis.label : string = "#sigma_{r_{calib.}}(tracker)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

**** Distribution of longitudinal position
#+BEGIN_SRC shell
  [name="CD::long_position" type="mygsl::histogram_1d"]
  #@config The histogram of the Geiger cell longitudinal position

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 100

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "mm"

  #@description The lower bound of the histogram
  min : real as length = 0 mm

  #@description The upper bound of the histogram
  max : real as length = 1500 mm

  #@description The X axis label
  display.xaxis.label : string = "z_{calib.}(tracker)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC
**** Distribution of longitudinal position error
#+BEGIN_SRC shell
  [name="CD::long_position_error" type="mygsl::histogram_1d"]
  #@config The histogram of the Geiger cell longitudinal position error

  #@description The group of the histogram (optional)
  group : string = "CD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 100

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "mm"

  #@description The lower bound of the histogram
  min : real as length = 0 mm

  #@description The upper bound of the histogram
  max : real as length = 10 mm

  #@description The X axis label
  display.xaxis.label : string = "#sigma_{z_{calib.}}(tracker)"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC

*** Tracker clustering data bank histograms
**** Number of clusters
#+BEGIN_SRC shell
  [name="TCD::nclusters" type="mygsl::histogram_1d"]
  #@config The histogram of the number of tracker clusters

  #@description The group of the histogram (optional)
  group : string = "TCD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 10

  #@description The lower bound of the histogram
  min : real = -0.5

  #@description The upper bound of the histogram
  max : real = 9.5

  #@description The X axis label
  display.xaxis.label : string = "N_{cluster}"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC
*** Tracker trajectory data bank histograms
#+BEGIN_SRC shell
  [name="TTD::helix_radius" type="mygsl::histogram_1d"]
  #@config The histogram of the helix radius

  #@description The group of the histogram (optional)
  group : string = "TTD::histos"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The number of bins
  number_of_bins : integer = 100

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "mm"

  #@description The lower bound of the histogram
  min : real as length = 0.0 mm

  #@description The upper bound of the histogram
  max : real as length = 2 m

  #@description The X axis label
  display.xaxis.label : string = "r_{helix}"

  #@description The Y axis label
  display.yaxis.label : string = "Counts"
#+END_SRC
