#+TITLE:  SuperNEMO control plot module
#+AUTHOR: Xavier Garrido
#+DATE:   2014-05-23
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration to run SuperNEMO simulations and
to produce several "control" plots. It provides one SN@ilWare module which
automatically plot physical quantities from different data banks. For example,
it shows the distribution of the number of Geiger hits from the =simulated_data=
bank and from the =calibrated_data= bank. The purpose of this module is to have
some fundamental key plots to check differences between software releases, new
software implementations and so on.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_control_plot]] under
=git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_control_plot_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* Module declaration

The next item holds the configuration of the module. The second item is related
to histogram declarations.

** Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_gt_studies_module.conf
:END:

The module name to be used when processing a file is =scp_module=.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC sh
  [name="gamma_tracking_studies_module" type="analysis::snemo_gamma_tracking_studies_module"]

  #@description A SuperNEMO module to evaluate gamma tracking performances
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram service][here]]
#+BEGIN_SRC sh
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC
*** Histogram storage
All histograms generated by =snemo_gamma_tracking_studies= module can be stored inside
ROOT files or XML archives.
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_output_files : string[2] as path =                     \
      "/tmp/${USER}/snemo.d/snemo_gamma_tracking_studies.root" \
      "/tmp/${USER}/snemo.d/snemo_gamma_tracking_studies.xml"
#+END_SRC
*** Histogram templates
Templates for histogram may be provided to reduce the amount of configuration of
individual histogram. For instance, plotting the energy distributions of several
channels may only need one general histogram definition which gives the x-axis
boundaries and x-binning.
#+BEGIN_SRC sh
  #@description The ouput file where to store the histograms
  Histo_template_files : string[1] as path = \
      "@SNEMO_SIMULATION_MODULES_DIR@/snemo_control_plot_histogram_templates.conf"
#+END_SRC

** Histogram declarations
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_gt_studies_histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section which is organized by data bank related plots. There are two kinds of
histograms:
- /unique/ histogram, dedicated to one task and used only one time,
- /template/ histogram which may be used by several data bank.
For example, to plot the distribution of the number of Geiger hits which can be
done for =simulated_data= and =calibrated_data= banks, we use *one* histogram
template that define boundaries, binning, axis titles... The /template/
histograms all belong to the =__template= group.

*** Mandatory preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
