#+TITLE:  SuperNEMO Detector Efficiency
#+AUTHOR: Xavier Garrido
#+DATE:   2014-05-23
#+OPTIONS: ^:{} num:nil toc:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration + source code to evaluate
SuperNEMO detector efficiency. Given a bank label to look into, the module
computes the efficiency of each sensitive detector volumes /i.e./ main wall
calorimeter, X-wall calorimeter, \gamma-vetos and Geiger cells. An example of
the use of this module is provided in this [[http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=2732][presentation]].

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_detector_efficiency]] under
=git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_detector_efficiency_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_detector_efficiency_module.conf
:END:

The next item holds the configuration for this module. The module name is
=detector_efficiency_module= which is needed when using =bxdpp_processing= as
explained in the top [[file:../README.org::*Use and execute a module][README]] file.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC sh
  [name="detector_efficiency_module" type="analysis::snemo_detector_efficiency_module"]

  #@description A SuperNEMO module to calculate the detector sensitivity
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "trace"
#+END_SRC

*** Geometry service label
Set the same geometry service label.
#+BEGIN_SRC sh
  #@description The Geometry Service label
  Geo_label : string = "Geo"
#+END_SRC
