#+TITLE:  SuperNEMO - \beta\beta studies
#+AUTHOR: Xavier Garrido
#+DATE:   2014-05-23
#+OPTIONS: ^:{} num:nil
#+STARTUP: entitiespretty

This repository holds a SN@ilWare configuration + source code to calculate \beta\beta0\nu
sensitivity for SuperNEMO experiment. Given 2\beta simulations (maybe data one day)
from 0\nu double decay and background simulations (2\nu,\nbsp^{208}Tl,\nbsp^{214}Bi...), the
module =snemo_bb0nu_halflife_limit= calculates signal/background efficiencies
and then determines the best sensitivity.

The current version is hosted at
[[https://github.com/xgarrido/snemo_simulation_modules/snemo_bb0nu_studies]] under
=git= version control.

The code itself is implemented in the =source= directory which holds the
=snemo_bb0nu_halflife_limit_module.*= source code as well as a =CMakeLists.txt=
file in order to compile, build and install the module following =cmake= rules.

* SuperNEMO \beta\beta0\nu module declaration

The next item holds the configuration for the SuperNEMO \beta\beta modules. The
second item is related to histogram declarations.

** Module declaration
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/snemo_bb0nu_studies_module.conf
:END:

The module name is =bb0nu_halflife_limit_module= which is needed when using
=bxdpp_processing= as explained in the top [[../README.org][README]] file.

*** File preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC
*** Declaration & description
#+BEGIN_SRC sh
  [name="bb0nu_halflife_limit_module" type="analysis::snemo_bb0nu_halflife_limit_module"]

  #@description A SuperNEMO module to calculate the 0nu sensitivity
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "error"
#+END_SRC

*** Histogram service label
Set the same histogram service label as defined [[Histogram service][here]]
#+BEGIN_SRC sh
  #@description The Histogram Service label
  Histo_label : string = "Histo"
#+END_SRC

*** Building histogram keys
The key fields are used to build different identifiants for histogram
dictionnary. The basic idea is to have this information inside =event_header=
and use it to build a =string= key. The program is then quite dynamic in the
sense that 0\nu halflife calculation can be done for different study purpose (just
change the =key_fields=).
#+BEGIN_SRC sh
  #@description The key fields from 'Event Header' bank to build a unique key for histogram
  key_fields : string[2] =     \
      "analysis.decay_process" \
      "analysis.source_isotope"
#+END_SRC

*** Experimental setup
Here we define the experimental conditions basically which isotope, mass, 2\beta
halflife, exposure are used.

**** Isotope values
#+BEGIN_SRC sh
  #@description The atomic mass number of the isotope
  experiment.isotope_mass_number : integer = 82

  #@description The total mass of the isotope
  experiment.isotope_mass : real as mass = 5 kg

  #@description The bb2nu halflife of the isotope
  experiment.isotope_bb2nu_halflife : real = 9.0e19 #year
#+END_SRC

**** Experiment exposure
#+BEGIN_SRC sh
  #@description The exposure time of the experiment
  experiment.exposure_time : real = 2.0 #year
#+END_SRC

** Histogram declarations
:PROPERTIES:
:MKDIRP: yes
:TANGLE: ../config/histogram_templates.conf
:END:

The histogram declarations /i.e./ name, boundaries, binning... are set in this
section. There are mostly /template/ histogram in such way, their declarations
may be used as templates for several histograms. For instance, the [[Energy
template]] defines an histogram that can be mimic by different analysis channels
/i.e./ O\nu energy distribution to background energy distribution.

*** Mandatory preamble
#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Energy template
#+BEGIN_SRC sh
  [name="energy_template" type="mygsl::histogram_1d"]
  #@description The title of the histogram (optional)
  title : string = ""

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}$E$_\text{calibrated}"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "dN/dE [A.U.]"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real = 2000.0

  #@description The upper bound of the histogram
  max : real = 3200.0
#+END_SRC
*** Efficiency template
#+BEGIN_SRC sh
  [name="efficiency_template" type="mygsl::histogram_1d"]
  #@config The histogram of the energy selection efficiency

  #@description The title of the histogram (optional)
  title : string = ""

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}\text{E}_\text{calibrated}\geq\text{E}_\text{cut}"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "efficiency"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real = 2000.0

  #@description The upper bound of the histogram
  max : real = 3200.0
#+END_SRC

*** Halflife limit template
#+BEGIN_SRC sh
  [name="halflife_template" type="mygsl::histogram_1d"]
  #@config The histogram of the energy selection efficiency

  #@description The title of the histogram (optional)
  title : string = ""

  #@description The group of the histogram (optional)
  group : string = "__template"

  #@description The build mode (default : "regular", "table", "mimic");
  mode : string = "regular"

  #@description The linear mode (default)
  linear : boolean = 1

  #@description The X axis label
  display.xaxis.label : string = "\Upsigma_\text{\tiny 1,2}\text{E}_\text{calibrated}\geq\text{E}_\text{cut}"

  #@description The X axis unit for display (a standard unit, typically SI or CLHEP)
  display.xaxis.unit : string = "keV"

  #@description The Y axis label
  display.yaxis.label : string = "halflife limit"

  #@description The number of bins
  number_of_bins : integer = 25

  #@description The unit of the bins' bounds (a standard unit, typically SI or CLHEP)
  unit : string = "keV"

  #@description The lower bound of the histogram
  min : real = 2000.0

  #@description The upper bound of the histogram
  max : real = 3200.0
#+END_SRC
